---
#roles/setup/vars

#Regions/Availability Zones
region: us-east-1
master_zones: us-east-1b
zones: us-east-1b,us-east-1c,us-east-1d

nodeCount: "{{ nodeCount }}"
nodeSize: "{{ nodeSize }}"
masterSize: "{{ masterSize }}"
...