---
#roles/deploy_pod/tasks

  - name: Adding container registery name to ECR URI
    replace:
      path: "{{ playbook_dir }}/../k8s/app/replication-controller.yaml"
      regexp: '.*'
      replace: '{{ ecr }}'
      after: ':[a-zA-Z0-9]*'
      before: '.dkr.ecr.us-east-1.amazonaws.com/'
      backup: no
  
  - name: Adding account id to ECR URI
    replace:
      path: "{{ playbook_dir }}/../k8s/app/replication-controller.yaml"
      regexp: '.*'
      replace: '{{ accountId }}'
      after: '.dkr.ecr.us-east-1.amazonaws.com/{{ ecr }}:*'
      before: '- image: '
      backup: no

  - name: Adding image tag to ECR URI
    replace:
      path: "{{ playbook_dir }}/../k8s/app/replication-controller.yaml"
      regexp: '.*'
      replace: '{{ tag }}'
      after: '\n    name: *'
      before: '.dkr.ecr.us-east-1.amazonaws.com/{{ ecr }}:*'
      backup: no

  - name: Container name
    replace:
      path: "{{ playbook_dir }}/../k8s/app/replication-controller.yaml"
      regexp: '.*'
      replace: '{{ containerName }}'
      after: '\n    ports:*'
      before: '    name: '
      backup: no

  - name: Application name
    replace:
      path: "{{ playbook_dir }}/../k8s/app/replication-controller.yaml"
      regexp: '.*'
      replace: '{{ appName }}'
      after: '\nspec:*'
      before: '    app: '
      backup: no

  - name: Pod name
    replace:
      path: "{{ playbook_dir }}/../k8s/app/replication-controller.yaml"
      regexp: '.*'
      replace: '{{ podName }}'
      after: '\n  labels:*'
      before: '  name: '
      backup: no

  - name: S3 Bucket name
    replace:
      path: "{{ playbook_dir }}/../k8s/app/configmap.yaml"
      regexp: '.*'
      replace: '{{ s3endpoint }}'
      after: '  s3_bucket: webapp.'
      backup: no

  - name: Deploy ConfigMap
    shell: "kubectl apply -f {{ playbook_dir }}/../k8s/app/configmap.yaml"

  - name: Deploy Secret
    shell: "kubectl apply -f {{ playbook_dir }}/../k8s/app/secret.yaml"

  - name: Deploy Load Balancer Service
    shell: "kubectl apply -f {{ playbook_dir }}/../k8s/app/loadbalancer.yaml"
  
  - name: Deploy Replication Controller Pod
    shell: "kubectl apply -f {{ playbook_dir }}/../k8s/app/replication-controller.yaml"

...