---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: helloworld
spec:
  ports:
    - port: 80
      name: lb
      targetPort: 8080
  selector:
    app: cloudappm
  type: LoadBalancer
...