---
apiVersion: v1               
kind: Pod                    
metadata:
  name: csye7374pod
  labels:                                                 
    app: csye7374webapp
spec:
  containers:
  - image: 946899997174.dkr.ecr.us-east-1.amazonaws.com/csye7374:csye7374image2
    name: csye7374container
    ports:
    - containerPort: 8080    
      protocol: TCP
    volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
  volumes:
    - name: foo
      secret:
        secretName: csye7374-config-db-config
        items:
        - key: DB_USER
          path: my-db/my-username
          mode: 511
#    env:
#      - name: SECRETS_DB_USERNAME
#        valueFrom:
#          secretKeyRef:
#            name: csye7374-config-db-config
#            key: DB_USER
#      - name: SECRETS_DB_URL
#        valueFrom:
#          secretKeyRef:
#            name: csye7374-config-db-config
#            key: DB_URL
#      - name: SECRETS_DB_PASSWORD
#        valueFrom:
#          secretKeyRef:
#            name: csye7374-config-db-config
#            key: DB_PASSWD
#      - name: SECRETS_S3_BUCKETNAME
#        valueFrom:
#          configMapKeyRef:
#            name: csye7374-app-config
#            key: s3_bucket
