---
apiVersion: v1               
kind: Pod                    
metadata:
  name: csye7374
  labels:                                                 
    app: csye7374         
spec:
  containers:
  - image: 727992775278.dkr.ecr.us-east-1.amazonaws.com/csye7374:latest
    name: csye7374            
    ports:
    - containerPort: 8080    
      protocol: TCP