---
apiVersion: v1               
kind: Pod                    
metadata:
  name: pod1
  labels:                                                 
    app: cloudapp
spec:
  containers:
  - image: 479392477648”.dkr.ecr.us-east-1.amazonaws.com/csye7374:latest4
    name: webapp
    ports:
    - containerPort: 8080    
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthcheck
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthcheck
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    env:
    - name: SECRETS_S3_BUCKETNAME
      valueFrom:
        configMapKeyRef:
          name: csye7374-app-config
          key: s3_bucket
    - name: SECRETS_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: csye7374-config-db-config
          key: DB_USER
    - name: SECRETS_DB_URL
      valueFrom:
        secretKeyRef:
          name: csye7374-config-db-config
          key: DB_URL
    - name: SECRETS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: csye7374-config-db-config
          key: DB_PASSWD
#    volumeMounts:
#      - name: foo
#        mountPath: "/etc/secrets"
#  volumes:
#    - name: foo
#      secret:
#        secretName: csye7374-config-db-config
#        items:
#         - key: DB_USER
#           path: my-db/my-username
#         - key: DB_PASSWD
#           path: my-db/my-password
#         - key: DB_URL
#           path: my-db/my-db-url