---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cloudapp-replica-controller
  labels:
    app: cloudapp
spec:
  replicas: 3
  selector:
    app: cloudapp
  template:
    metadata:
      name: cloudapp-pod
      labels:
        app: cloudapp
    spec:
      containers:
        - name: cloudapp-container
          image: 727992775278.dkr.ecr.us-east-1.amazonaws.com/csye7374:latest11
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 100
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 100
          env:
            - name: SECRETS_S3_BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  name: csye7374-app-s3-configmap
                  key: s3_bucket
            - name: SECRETS_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: csye7374-db-secret
                  key: DB_USER
            - name: SECRETS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: csye7374-db-secret
                  key: DB_URL
            - name: SECRETS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csye7374-db-secret
                  key: DB_PASSWD
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
...