---
apiVersion: v1               
kind: ReplicationController                    
metadata:
  name: cloudapp-replica-controller
  labels:
    app: replication-controller
spec:
  replicas: 3
  selector: 
    app: cloudapp
  template:
    metadata: 
      name: cloudapp-pod
      labels:
        app: cloudapp
    spec:
      containers:
      - name: cloudapp-container
        image: 727992775278.dkr.ecr.us-east-1.amazonaws.com/csye7374:latest5
        ports:
        - containerPort: 8080    
          protocol: TCP
        env:
        - name: SECRETS_S3_BUCKETNAME
          valueFrom:
            configMapKeyRef:
              name: csye7374-app-config
              key: s3_bucket
        - name: SECRETS_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: csye7374-config-db-config
              key: DB_USER
        - name: SECRETS_DB_URL
          valueFrom:
            secretKeyRef:
              name: csye7374-config-db-config
              key: DB_URL
        - name: SECRETS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: csye7374-config-db-config
              key: DB_PASSWD
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
...