---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cloudapp-replica-controller
  labels:
    app: csye7374webapp
spec:
  replicas: 3
  selector:
    app: csye7374webapp
  template:
    metadata:
      name: latestpod3
      labels:
        app: csye7374webapp
    spec:
      containers:
        - name: csye7374container
          image: 946899997174.dkr.ecr.us-east-1.amazonaws.com/csye7374:latestimage3
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: SECRETS_S3_BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  name: csye7374-app-config
                  key: s3_bucket
            - name: SECRETS_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: csye7374-config-db-config
                  key: DB_USER
            - name: SECRETS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: csye7374-config-db-config
                  key: DB_URL
            - name: SECRETS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csye7374-config-db-config
                  key: DB_PASSWD
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
...