---
apiVersion: v1
kind: Secret
metadata:
  name: csye7374-config-db-config
stringData:
  DB_USER: csye7374
  DB_URL: jdbc:mysql://mydbinstance1.cgkazer7p57q.us-east-1.rds.amazonaws.com/csye7374
data:
  DB_PASSWD: csye7374