---
apiVersion: v1
kind: Service
metadata:
  name: csye7374-l5-02-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30130
  selector:
    app: csye7374webapp