Master:
  Cpu: 500m
  Memory: 1024Mi
  NumExecutors: 2
  SecretsFilesSecret: my-secret
  ContainerEnv:
    - name: GITHUB_USER
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: github-secret-user
    - name: GITHUB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: github-secret-password
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: aws-secret-access-key
    - name: AWS_ACCOUNT_ID
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: aws-account-id
  OverwritePlugins: true
  InstallPlugins:
    - github:latest
    - kubernetes:1.14.0
    - workflow-job:2.31
    - workflow-aggregator:2.6
    - credentials-binding:1.17
    - aws-credentials:latest
    - amazon-ecr:latest
    - git:3.9.1
    - build-timestamp:latest
  JCasC:
    enabled: true
    ConfigScripts:
      github-credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope:       GLOBAL
                      id:          github-user
                      username:    ${GITHUB_USER}
                      password:    ${GITHUB_PASSWORD}
                      description: Github Credentials
                  - aws:
                      scope:       GLOBAL
                      id:          aws-kops-user
                      accessKey:   ${AWS_ACCESS_KEY_ID}
                      secretKey:   ${AWS_SECRET_ACCESS_KEY}
                      description: AWS Credentials
                  - string:
                      scope: GLOBAL
                      id: aws-account-id
                      secret: ${AWS_ACCOUNT_ID}
                      description: AWS Account ID
  Jobs:
    csye7374-job: |-
      <flow-definition plugin="workflow-job@2.31">
      <description/>
        <keepDependencies>false</keepDependencies>
        <properties>
          <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
          <triggers>
          <com.cloudbees.jenkins.GitHubPushTrigger plugin="github@1.29.4">
          <spec/>
          </com.cloudbees.jenkins.GitHubPushTrigger>
          </triggers>
          </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
        </properties>
        <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2.65">
          <scm class="hudson.plugins.git.GitSCM" plugin="git@3.9.1">
            <configVersion>2</configVersion>
            <userRemoteConfigs>
            <hudson.plugins.git.UserRemoteConfig>
            <url>https://github.com/{{githubUsername}}/csye7374-spring2019</url>
            <credentialsId>github-user</credentialsId>
            </hudson.plugins.git.UserRemoteConfig>
            </userRemoteConfigs>
            <branches>
            <hudson.plugins.git.BranchSpec>
            <name>*/{{branchName}}</name>
            </hudson.plugins.git.BranchSpec>
            </branches>
            <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
            <submoduleCfg class="list"/>
            <extensions/>
          </scm>
          <scriptPath>Jenkinsfile</scriptPath>
          <lightweight>true</lightweight>
      </definition>
      <triggers/>
      <disabled>false</disabled>
      </flow-definition>
Agent:
  Cpu: 500m
  Memory: 1024Mi
rbac:
  install: false
  serviceAccountName: jenkins-svc-account
  roleRef: cluster-admin
  roleKind: ClusterRole
  roleBindingKind: ClusterRoleBinding6