---
#roles/setup_grafana/tasks

- name: Setup Grafana Dashboard
  shell: helm install --name grafana stable/grafana

- name: Sleep for 60 seconds and allowing Pods to run
  wait_for: timeout=60
  delegate_to: localhost

#    helm:
#      host: localhost
#      chart:
#        name: grafana
#      state: present
#      name: my-grafana
#      namespace: default

- name: Exporting pod name as env variable
  shell: kubectl get pods --namespace default -l "app=grafana,release=grafana" -o jsonpath="{.items[0].metadata.name}"
  register: pod_name

- name: Port Forwarding Grafana with our Pods to 3000
  shell: kubectl --namespace default port-forward {{ pod_name.stdout }} 3000

...