---
  - name: Create kubernetes cluster
    hosts: localhost
    roles:
      - kops/common
      - kops/setup_cluster
      - kops/setup_helm
      - kops/setup_metrics-server
      - kops/deploy_dashboard
...