---
  - name: Create Cloud Resources
    hosts:  localhost
    vars:
      rdsSubnetGroup: "subnetGroup-rds-csye6225-spring2018-singhvika.me"
    tasks:
      - name: Get VpcId
        shell:  aws ec2 describe-vpcs --filters '[{"Name":"tag:KubernetesCluster","Values":["k8s.csye6225-spring2018-singhvika.me"]}]' --query 'Vpcs[0].VpcId' | grep -oP "([a-zA-Z0-9\.\-])*"
        register: vpcId
      
      - name: Get Factsss
        ec2_vpc_subnet_facts:
          filters:
            vpc-id: "{{vpcId.stdout}}"
        register: subnet_facts

      - name: Get SubnetList from facts
        vars:
          subnet_ids: "{{ subnet_facts.subnets|map(attribute='id')|list }}"
        debug:
          msg: "ids {{subnet_ids[0]}}"

      - name: ASDSAD
        debug:
          msg: "OK {{subnet_ids}}"
...
