rbac:
  create: true
  pspEnabled: true
  pspUseAppArmor: true
  namespaced: false
serviceAccount:
  create: true
  name: grafana-svc-account

replicas: 1

deploymentStrategy: RollingUpdate

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10

image:
  repository: grafana/grafana
  tag: 6.0.0
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 472
  fsGroup: 472


extraConfigmapMounts: []

downloadDashboardsImage:
  repository: appropriate/curl
  tag: latest
  pullPolicy: IfNotPresent

chownDataImage:
  repository: busybox
  tag: 1.30.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  annotations: {}
  labels: {}

ingress:
  enabled: false
  annotations: {}
  labels: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraContainers: |

persistence:
  enabled: true
  initChownData: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

adminUser: admin
# adminPassword: strongpassword

admin:
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password

env: {}

envFromSecret: ""

extraSecretMounts: []

extraVolumeMounts: []

plugins: []

dashboardProviders: {}

dashboards: {}

dashboardsConfigMaps: {}

grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net

ldap:
  existingSecret: ""
  config: ""

smtp:
  existingSecret: ""
  userKey: "user"
  passwordKey: "password"

sidecar:
  image: kiwigrid/k8s-sidecar:0.0.11
  imagePullPolicy: IfNotPresent
  resources: {}
  dashboards:
    enabled: false
    label: grafana_dashboard
    folder: /tmp/dashboards
    searchNamespace: null
  datasources:
    enabled: false
    label: grafana_datasource
    searchNamespace: null