---
#roles/setup_fluentd/tasks

  - name: Get aws account id
    shell: "aws sts get-caller-identity --output text --query 'Account'"
    register: accountId

  - name: Install fluentd
    shell: "helm install --name fluentd incubator/fluentd-cloudwatch -f values_fluentd.yaml --set awsRole=arn:aws:iam::{{ accountId.stdout }}:role/nodes.{{ clusterName }},extraVars[0]=\"\\{ name: FLUENT_UID\\, value: '0' \\}\""

...