#roles/setup_helm/tasks
---
  - name: Tiller service account
    shell: "kubectl -n kube-system create serviceaccount tiller"

  - name: Tiller cluser-role binding
    shell: "kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller"

  - name: Initialize Helm
    shell: "helm init --service-account tiller"

  - name: Deploy Tiller
    shell: "kubectl patch deploy --namespace kube-system tiller-deploy -p '{\"spec\":{\"template\":{\"spec\":{\"serviceAccount\":\"tiller\"}}}}'"
...