---
apiVersion: v1
kind: Secret
metadata:
  name: csye7374-db-secret
type: Opaque
stringData:
  DB_USER: {{rdsUsername}}
  DB_URL: jdbc:mysql://{{rdskubernetes.instance.endpoint}}:3306/{{rdsDbName}}
data:
  DB_PASSWD: {{rdsPassword | b64encode}}
...